language: go

go:
  - tip # The latest version of Go.

  script:
  - go build service/main.go
  - go build cli/main.go
  - go test ./service/entity
  - go test ./cli/cmd

  branches:
  only:
    - master